## Import required libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from matplotlib import cm

from matplotlib import font_manager
font_path = 'C://Users//amita//AppData//Local//Microsoft//Windows//Fonts/Barlow-Regular.ttf'  # Your font path goes here
font_manager.fontManager.addfont(font_path)
prop = font_manager.FontProperties(fname=font_path)

plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = prop.get_name()

In [10]:
# Load data into a pandas dataframe
df = pd.read_csv('chowdary.csv', index_col=0)

# Print the dimensions of the dataset
print("Number of rows: ", df.shape[0])
print("Number of columns: ", df.shape[1])

Number of rows:  104
Number of columns:  183

In [11]:
# Print the first 5 rows of the dataset
df.head()

,tumour,X201123_s_at,X201262_s_at,X201496_x_at,X201497_x_at,X201525_at,X201884_at,X201909_at,X202018_s_at,X202037_s_at,...,X219404_at,X219508_at,X219580_s_at,X219768_at,X221004_s_at,X221245_s_at,X221879_at,X37892_at,X44790_s_at,X60474_at
GSM85863,B,38.5,77.2,10.0,10.0,65.7,12.9,10.4,30.1,418.6,...,10.0,10.0,10.0,52.8,61.0,10.7,30.5,364.0,10.0,10.0
GSM85864,B,82.7,13.4,31.8,338.4,93.3,810.5,115.8,10.0,19.6,...,58.3,10.0,61.6,10.0,100.5,58.0,69.7,62.7,95.6,130.4
GSM85865,B,54.8,111.1,16.3,119.0,361.3,11.9,11.3,1247.7,166.8,...,18.0,11.7,38.6,514.2,35.6,10.0,37.5,151.9,13.4,10.0
GSM85866,B,41.1,96.3,11.2,76.4,435.5,16.9,14.1,1179.3,259.0,...,10.0,24.9,116.0,461.5,29.6,10.0,36.1,107.1,20.1,10.0
GSM85867,B,30.5,117.3,18.4,139.4,917.0,11.3,10.0,244.8,173.3,...,11.0,10.0,22.6,213.6,23.0,10.0,10.2,127.5,17.6,10.0

### Check for missing values

In [54]:
# print(df.isnull().sum())
print(df.isnull().sum().sum())

0

### Check the distribution of the tumour variable

In [19]:
print(df['tumour'].value_counts())

B    62
C    42
Name: tumour, dtype: int64

### Finding the count of correlations present

In [214]:
corr_matrix = df.drop('tumour', axis=1).corr()
corr_matrix

,X201123_s_at,X201262_s_at,X201496_x_at,X201497_x_at,X201525_at,X201884_at,X201909_at,X202018_s_at,X202037_s_at,X202286_s_at,...,X219404_at,X219508_at,X219580_s_at,X219768_at,X221004_s_at,X221245_s_at,X221879_at,X37892_at,X44790_s_at,X60474_at
X201123_s_at,1.000000,0.693919,0.142524,0.359387,0.223427,0.740989,0.651331,-0.048749,0.323667,-0.107905,...,0.637985,0.490054,0.481913,-0.002949,0.386018,0.728266,0.731273,0.478370,0.601135,0.638844
X201262_s_at,0.693919,1.000000,0.182001,0.355458,0.395168,0.347871,0.805716,0.102249,0.435427,0.083957,...,0.243547,0.118223,0.166256,0.038700,0.091710,0.168403,0.193311,0.596180,0.076178,0.138261
X201496_x_at,0.142524,0.182001,1.000000,0.831018,0.009270,0.285698,0.158831,-0.092797,0.230887,-0.208364,...,0.182451,0.152632,0.123412,-0.120233,0.221710,0.181841,0.224739,0.082288,0.129419,0.158683
X201497_x_at,0.359387,0.355458,0.831018,1.000000,0.125484,0.571099,0.366042,-0.072267,0.425509,-0.173306,...,0.439535,0.385005,0.365263,-0.105274,0.463643,0.386351,0.467271,0.295209,0.232475,0.313525
X201525_at,0.223427,0.395168,0.009270,0.125484,1.000000,0.059445,0.309982,0.542397,0.418924,0.392572,...,0.014706,-0.057505,0.027436,0.332790,-0.012493,-0.041302,0.007121,0.244999,-0.057049,-0.039805
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
X221245_s_at,0.728266,0.168403,0.181841,0.386351,-0.041302,0.924534,0.251103,-0.177381,0.105561,-0.300226,...,0.869360,0.759920,0.746890,-0.150282,0.648593,1.000000,0.963219,0.140737,0.848650,0.876262
X221879_at,0.731273,0.193311,0.224739,0.467271,0.007121,0.924469,0.237973,-0.143033,0.202266,-0.253272,...,0.878493,0.745038,0.723002,-0.100136,0.708065,0.963219,1.000000,0.184005,0.802778,0.851616
X37892_at,0.478370,0.596180,0.082288,0.295209,0.244999,0.351229,0.731631,-0.004572,0.227027,0.276512,...,0.148976,0.042955,0.175624,0.030914,0.010061,0.140737,0.184005,1.000000,0.103972,0.118157
X44790_s_at,0.601135,0.076178,0.129419,0.232475,-0.057049,0.789389,0.151458,-0.152184,0.000015,-0.241719,...,0.566829,0.352723,0.563067,-0.096772,0.219658,0.848650,0.802778,0.103972,1.000000,0.951296
X60474_at,0.638844,0.138261,0.158683,0.313525,-0.039805,0.861326,0.198162,-0.149613,0.057064,-0.261364,...,0.703086,0.476925,0.720256,-0.103022,0.348469,0.876262,0.851616,0.118157,0.951296,1.000000

### Let's create a dataframe with two column comparison

In [215]:
# Convert the correlation matrix to a DataFrame
corr_df = pd.DataFrame(corr_matrix.unstack().sort_values(ascending=False),
                       columns=['correlation coefficient'])

# Reset the index to create separate columns for variable 1 and variable 2
corr_df = corr_df.reset_index()

# Rename the columns
corr_df.columns = ['variable 1', 'variable 2', 'corr coef']

corr_df = corr_df[corr_df['variable 1'] != corr_df['variable 2']]

corr_df['deleter'] = corr_df.apply(lambda x:''.join(sorted([x['variable 1'], x['variable 2']])), axis=1)
corr_df.drop_duplicates(subset=['deleter'], inplace=True)


corr_df.drop('deleter', axis=1, inplace=True)
# Print the new DataFrame
corr_df

         variable 1    variable 2  corr coef
182      X214142_at    X207214_at   0.996833
184    X216401_x_at  X217378_x_at   0.995421
186    X217378_x_at  X216576_x_at   0.995384
188      X214777_at  X216401_x_at   0.993978
190    X216576_x_at  X216401_x_at   0.993867
...             ...           ...        ...
33114  X209602_s_at    X203256_at  -0.305438
33116  X202286_s_at    X206430_at  -0.305772
33118  X202286_s_at    X205476_at  -0.309115
33120  X202286_s_at    X202831_at  -0.317065
33122  X202286_s_at    X204580_at  -0.335186

[16471 rows x 3 columns]

### Now above we have unique column combinations and their correlation coefficient value. Let's see how many are above usual threshold - 60%

In [218]:
out = corr_df[abs(corr_df['corr coef'])>0.6]
out

        variable 1    variable 2  corr coef
182     X214142_at    X207214_at   0.996833
184   X216401_x_at  X217378_x_at   0.995421
186   X217378_x_at  X216576_x_at   0.995384
188     X214777_at  X216401_x_at   0.993978
190   X216576_x_at  X216401_x_at   0.993867
...            ...           ...        ...
8192    X206312_at    X203256_at   0.600565
8194    X209211_at    X207529_at   0.600399
8196  X211798_x_at    X212592_at   0.600370
8198    X213880_at  X208121_s_at   0.600304
8200  X217157_x_at    X204320_at   0.600177

[4010 rows x 3 columns]

### Total number of columns that are correlated to another

In [241]:
len(set(np.append(out['variable 1'].unique(), out['variable 2'].unique())))

172

### That's a really high amount of correlated columns

## Let's calculate VIF

In [186]:
from statsmodels.stats.outliers_influence import variance_inflation_factor as vif

In [187]:
vif_df = pd.DataFrame()
vif_df["VIF Factor"] = [vif(X.values, i) for i in range(X.shape[1])]
vif_df["features"] = X.columns

print(vif_df)

C:\Users\amita\anaconda3\envs\ml_final\lib\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

     VIF Factor      features
0           inf  X201123_s_at
1           inf  X201262_s_at
2           inf  X201496_x_at
3           inf  X201497_x_at
4           inf    X201525_at
..          ...           ...
177         inf  X221245_s_at
178         inf    X221879_at
179         inf     X37892_at
180         inf   X44790_s_at
181         inf     X60474_at

[182 rows x 2 columns]

### Since VIF is calculated with help of R_square value and R_square increases with increase in number of variables, we see that VIF is infinite for all the variables. You can see below how there's an increase with increasing number of variables in the dataset

In [195]:
for val in range(10, 121, 10):
    print(f'VIF for column 3 with {val}  columns is: {vif(X.values[:,0:val], 3)}')

VIF for column 3 with 10  columns is: 8.223964708460501
VIF for column 3 with 20  columns is: 11.236071054583995
VIF for column 3 with 30  columns is: 22.918323919653364
VIF for column 3 with 40  columns is: 71.83366907754584
VIF for column 3 with 50  columns is: 79.30434993928823
VIF for column 3 with 60  columns is: 103.46993338964649
VIF for column 3 with 70  columns is: 122.76253035436912
VIF for column 3 with 80  columns is: 362.5838225297922
VIF for column 3 with 90  columns is: 1288.458714506455
VIF for column 3 with 100  columns is: 38531.708182085764
VIF for column 3 with 110  columns is: inf
VIF for column 3 with 120  columns is: inf

In [193]:
for val in range(10, 121, 10):
    print(f'VIF for column 7 with {val}  columns is: {vif(X.values[:,0:val], 7)}')

VIF for column 7 with 10  columns is: 2.285171725186038
VIF for column 7 with 20  columns is: 2.6674891132837293
VIF for column 7 with 30  columns is: 3.1562488714672416
VIF for column 7 with 40  columns is: 3.699315807986315
VIF for column 7 with 50  columns is: 7.258738465581199
VIF for column 7 with 60  columns is: 8.422889589213872
VIF for column 7 with 70  columns is: 14.080060211930478
VIF for column 7 with 80  columns is: 23.44446045887124
VIF for column 7 with 90  columns is: 65.07458719635115
VIF for column 7 with 100  columns is: 389.7827256012898
VIF for column 7 with 110  columns is: inf
VIF for column 7 with 120  columns is: inf

### We can see how with increase in number of variables, VIF increases

### Creating a custom VIF that uses adjusted R_square instead of usual R_square

In [198]:
from statsmodels.regression.linear_model import OLS

def vif_adjusted(X, exog_idx):
    """
    Compute the variance inflation factor (VIF) for a given feature in a dataset, using the adjusted R squared.
    
    Parameters
    ----------
    X : array_like
        The design matrix, with shape (n_samples, n_features).
    exog_idx : int
        The index of the feature for which to compute the VIF.
        
    Returns
    -------
    vif : float
        The variance inflation factor for the given feature.
    """
    # Extract the feature for which to compute the VIF
    exog = X[:, exog_idx]
    
    # Compute the OLS regression model for the feature against all other features, including an intercept term
    ols_model = OLS(endog=exog, exog=X[:, np.arange(X.shape[1]) != exog_idx], hasconst=True)
    ols_result = ols_model.fit()
    
    # Compute the VIF using the adjusted R squared value
    vif = 1 / (1 - ols_result.rsquared_adj)
    
    return vif

In [199]:
for val in range(10, 121, 10):
    print(f'Adj VIF for column 3 with {val}  columns is: {vif_adjusted(X.values[:,0:val], 3)}')

Adj VIF for column 3 with 10  columns is: 6.776028373285434
Adj VIF for column 3 with 20  columns is: 8.283307334595793
Adj VIF for column 3 with 30  columns is: 14.907831977666376
Adj VIF for column 3 with 40  columns is: 40.49596746289499
Adj VIF for column 3 with 50  columns is: 37.829453874302324
Adj VIF for column 3 with 60  columns is: 40.38285837448393
Adj VIF for column 3 with 70  columns is: 37.265267956606635
Adj VIF for column 3 with 80  columns is: 78.61742308678475
Adj VIF for column 3 with 90  columns is: 167.62243254230808
Adj VIF for column 3 with 100  columns is: 1670.9314735960827
Adj VIF for column 3 with 110  columns is: nan
Adj VIF for column 3 with 120  columns is: nan

C:\Users\amita\anaconda3\envs\ml_final\lib\site-packages\statsmodels\regression\linear_model.py:1765: RuntimeWarning: divide by zero encountered in divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
C:\Users\amita\anaconda3\envs\ml_final\lib\site-packages\statsmodels\regression\linear_model.py:1765: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)

In [200]:
for val in range(10, 121, 10):
    print(f'Adj VIF for column 7 with {val}  columns is: {vif_adjusted(X.values[:,0:val], 7)}')

Adj VIF for column 7 with 10  columns is: 1.622193742876379
Adj VIF for column 7 with 20  columns is: 1.694267016258496
Adj VIF for column 7 with 30  columns is: 1.7688572190362004
Adj VIF for column 7 with 40  columns is: 1.7967805583155758
Adj VIF for column 7 with 50  columns is: 2.9832119719100443
Adj VIF for column 7 with 60  columns is: 2.8322650706754535
Adj VIF for column 7 with 70  columns is: 3.6824158497851722
Adj VIF for column 7 with 80  columns is: 4.379661302374318
Adj VIF for column 7 with 90  columns is: 7.293952918519783
Adj VIF for column 7 with 100  columns is: 14.563067660650326
Adj VIF for column 7 with 110  columns is: nan
Adj VIF for column 7 with 120  columns is: nan

### The values don't seem to be inflated anymore but we do notice a new issue, we are getting nan now. This is mainly due to number of variables being more than number of rows.

### So we need to find an alternative method to solve this multicollinearity problem